### ISSUE TITLE
Dynamically inserted paper-items are not usable

### ISSUE THREAD

**Issue by bobslaede** [PolymerElements/paper-menu#21]
Creating a paper-item DOM element and inserting it, creates an item that cannot be selected from the paper-menu.

This is a GIF of the error.

![paper-menu](https://cloud.githubusercontent.com/assets/437918/8033397/56323fce-0dde-11e5-9e37-91c2df2b923d.gif)

Expected result: The paper-item should work like any other paper-item already in the DOM when starting.

**Comment by mojtabashabani** [comment]
I have same issue in my project , please fix this

**Comment by Inrego** [comment]
Same problem here - however in my case I bind add a `<template is="dom-repeat">` in `paper-menu`, in order to bind the items to an array, like this:

```
<paper-menu attr-for-selected="Value" selected="{{config.ComPort}}">
    <template is="dom-repeat" items="{{config.ComPorts}}">
        <paper-item>{{item.Name}}</paper-item>
    </template>
</paper-menu>
```

This causes only the first item to be selectable - and it will be selected no matter which item i click.

**Comment by shashi** [comment]
If you do `Polymer.dom($0).appendChild` instead of `$0.appendChild`, this works. (This is due to [shady DOM](https://www.polymer-project.org/1.0/articles/shadydom.html) in Polymer 1.0.)

_However_, if you do this, the selected index of the newly added menu items is **4 more than** what is should be!

**Comment by miztroh-zz** [comment]
@morethanreal: Any updates on this?  Not being able to use `dom-repeat` to generate menu items is a real drag.

**Comment by miztroh-zz** [comment]
@morethanreal: Nevermind. My issue was due to https://github.com/PolymerElements/iron-selector/issues/57.

**Comment by ValueBC** [comment]
Yup, I just found this bug as well.

**Comment by naoak** [comment]
It seems this bug was fixed by PolymerElements/iron-selector#68.

**Comment by Gwalks91** [comment]
Any updates on this?

**Comment by s-devaney** [comment]
Still having this issue.

**Comment by s-devaney** [comment]
For those who are struggling with this -

If you try and dynamically insert a `paper-item` as a direct child within an instantiated `paper-menu` it will not work. The `paper-item` must be part of the `paper-menu`'s shadow DOM. To do this:

`Polymer.dom(paperMenu).appendChild(paperItem);` and then `paperMenu._updateItems();`

This is a limitation of using a shadow DOM model. The reason I require a workaround is that I'm trying to use Polymer with an MVC framework which renders views this way.

Given Polymer's encapsulation of elements I am fully aware that this approach will require hacky work-arounds such as the one above, but Polymer doesn't provide enough application structure at present (IMO).

**Comment by bicknellr** [comment]
This seems fixed - [here's a JSBin to try out](http://jsbin.com/yiwulatiha/edit?html,output).

@s-devaney: Like @shashi said, this is a result of [shady DOM](https://www.polymer-project.org/1.0/articles/shadydom.html) - Polymer's approximation of shadow DOM. Shady DOM doesn't use native shadow DOM features unless explicitly asked but it gives the appearance of shadow DOM availability through the `Polymer.dom` wrapper. [You can read more about Polymer's DOM API here.](https://www.polymer-project.org/1.0/docs/devguide/local-dom.html) Given shady DOM's implementation uses the regular DOM to make events / layout work as expected, you have to use the wrapper to manipulate anything using shady DOM - i.e. Polymer elements and their descendants.

So, you have to say `Polymer.dom(paperMenu).appendChild(paperItem);` rather than just `paperMenu.appendChild(paperItem);` even though you're looking to add `paperItem` as a normal child of `paperMenu` rather than in its shadow tree. (Shady DOM's equivalent of `.shadowRoot` is `.root`, which you can use to manipulate its shadow tree.) Shady DOM might not actually place non-shadow children of `paperMenu` where true children of `paperMenu` are, so `paperMenu.appendChild` won't work as expected. (In fact, it doesn't put them there because `paper-menu` has [stuff in its shadow root](https://github.com/PolymerElements/paper-menu/blob/dd783ba26cca7ca371e823dc49d757f449178d8c/paper-menu.html#L86).)
