### ISSUE TITLE
bug in paper-submenu inside a multi-select outer menu

### ISSUE THREAD

**Issue by shashi** [PolymerElements/paper-menu#35]
for every tap in the submenu the selection of the item containing the submenu toggles in the parent menu. what would be a reasonable behavior here anyway?

**Comment by notwaldorf** [comment]
What do you mean by toggles? The idea is that if you select something in the submenu, the parent item should be selected. Do you have a jsbin of the bug you're seeing?

**Comment by shashi** [comment]
I could not get a runnable URL from jsbin, so here's the gist with the code https://gist.github.com/anonymous/c5ff81cbae2d3b97c536

the second menu item is a submenu, I log `.selectedValues`  on `iron-select` and `iron-deselect`, only odd number of times I click on an item in the submenu, `.selectedValues` contains `1`.

**Comment by bicknellr** [comment]
I think this issue is resolved as of [this commit](https://github.com/PolymerElements/iron-menu-behavior/commit/19c24ab38da788a6ac5b8e98ac355a856e6c8371) which stops the event that selects the item from bubbling to the outer menu. [Here's a modified version of your demo.](http://jsbin.com/geyodi/edit?html,console,output) If you click on items inside the submenu, `selectedValues` of the outer menu doesn't change.
