### ISSUE TITLE
paper-menu selection incorrect when using paper-submenu

### ISSUE THREAD

**Issue by s-devaney** [PolymerElements/paper-menu#42]
When creating using paper-menu with paper-submenu children the selected attribute of the paper-menu doesn't account for the paper-items within the paper-submenu.

**Expected functionality:**
_-paper-menu_
--- paper-item (selection 0)
--- paper-item (selection 1)
--- paper-submenu
------ paper-item (selection 2)
------ paper-item (selection 3)
--- paper-item (selection 4)

**Currently:**
_-paper-menu_
--- paper-item (selection 0)
--- paper-submenu
------ paper-item (selection 1)
------ paper-item (selection 1)
------ paper-item (selection 1)
--- paper-item (selection 2)

**Comment by RossRothenstine** [comment]
+1 As a workaround, we had to data bind the submenus backwards up into the original menu. Very troublesome, even when using "attr-for-selected".

**Comment by bicknellr** [comment]
@s-devaney: The paper-submenu acts as a single item of its parent menu rather than inserting its items into the items of the parent menu. So, your tree above ends up being something like this:

``` html
<paper-menu id="outer">
  <paper-item>item 0 of #outer</paper-item>
  <paper-submenu><!-- actual item 1 of #outer -->
    <paper-item class="menu-trigger">
      displayed as if item 1 of #outer
    </paper-item>
    <paper-menu id="inner" class="menu-content">
      <paper-item>item 0 of #inner</paper-item>
      <paper-item>item 1 of #inner</paper-item>
      <paper-item>item 2 of #inner</paper-item>
    </paper-menu>
  </paper-submenu>
  <paper-item>item 2 of #outer</paper-item>
</paper-menu>
```

To determine the selection path within a nested set of menus, you'll need to recurse through them ([demo](http://jsbin.com/nisejef/edit?html,console,output)). But, if you don't actually care about the path / index and just need to know what thing was selected and when, you can listen for the `iron-select`~~`ed`~~ event at the root menu and assign some key to the item to be read back out (`xyz` attribute in the demo). Are you (/ anyone else reading this) running into a situation where it's actually important to know the index of an item in the menu as if it were flat? I'm finding it hard to think of a good use case.

**Comment by bicknellr** [comment]
Closing - I think the comment above should be a reasonable explanation of how to handle this. Let me know if it isn't!

**Comment by pravin-d** [comment]
@bicknellr  Hey hi.. I'm having a very similar issue. I want only the selected item. Path is not required. However I was just curious about the behaviour of your menu items. When a 1st level child paper-item is selected, the paper-submenu items that are open collapse. Any Idea how this is happening ? 
Sorry for posting here.. did not where else to do so

**Comment by bicknellr** [comment]
Hi @pravin-d, elements with IronSelectableBehavior have `multi` set to false by default. This property is inherited from IronSelectableBehavior and when it's false, allows only one thing to be selected at a time. If you add it to paper-menu, it will allow multiple items in that menu to be selected simultaneously, which means those menus can be open simultaneously. [Here's an example.](http://jsbin.com/sutavom/edit?html,output)
