### ISSUE TITLE
documentation states items() method, but it is an array

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/paper-menu#52]
![paper-menu-items-prop](https://cloud.githubusercontent.com/assets/97242/10256997/a8f64f94-6909-11e5-9f66-1cb1dad3a1c4.png)

See screenshot from the docs here: https://elements.polymer-project.org/elements/paper-menu

**Comment by notwaldorf** [comment]
hmmm, `items()` is a getter (https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L157), so i think that's why it's getting document as a method (which it technically is)

@garlicnation @cdata what do you think hydrolysis should do in this case? Show it as a getter method, or as an accessible property?

**Comment by notwaldorf** [comment]
Ah apparently https://github.com/Polymer/hydrolysis/issues/144 is already a thing, closing since this isn't a paper-menu issue.
