### ISSUE TITLE
Cannot select when item is distributed into shadow DOM

### ISSUE THREAD

**Issue by tpluscode** [PolymerElements/paper-menu#82]
Hi. I'm not sure whether this an issue of `<paper-menu>` or `<paper-item>`, so sorry if I'm raising this in the wrong repository.

In [this plunk](https://plnkr.co/edit/FSNddcCd5amGQqYpXWeD?p=preview) demonstrate how it's not possible to select a `<paper-item>`, when it's content is distributed into the Shadow DOM. Clicking a distributed `<span>` does nothing. It is still possible to select an item by clicking around it, though.

This problem does not occur with Shady DOM (when you comment out the top script).

**Comment by tpluscode** [comment]
I see that this is similar to #21 but I don't think it's the same issue, is it?

**Comment by notwaldorf** [comment]
In your plunkr, clicking selects the items fine (but it's using an older version of paper-item which has a selection quirk), so here it is as a jsbin, with all the latest releases of the elements: http://jsbin.com/rucude/edit?html,output

Closing, as this is no longer an issue.

**Comment by tpluscode** [comment]
Unfortunately your sample doesn't work either. Sure it selects fine when you click the item but does not select when you click the distributed label.

I tweaked [my plunk](https://plnkr.co/edit/FSNddcCd5amGQqYpXWeD?p=preview) so that it's clear, where to click :wink:

**Comment by notwaldorf** [comment]
Ok. @cdata found a workaround, which is to set `pointer-events:none` to your distributed `paper-item` content. Here's the updated plunkr to demo that: https://plnkr.co/edit/gsQrm5iClsejvjCkGhwc?p=preview

This is a bit of a scary change to add to `paper-item` itself, since we have no guarantee it won't break other people (my experience with `paper-item` is that everybody uses it in ways I haven't thought about), and this is a bit of an edge case to begin with. 

Anyway, this should fix your issue.

**Comment by tpluscode** [comment]
Nice workaround. Thank you

**Comment by notwaldorf** [comment]
Glad this worked out!
